mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[highlight_sql]": true
    show-sql: true
